schema: "classroom50/repo-config/v1"
classroom: "data-tech-analytics"
assignment: "hello-github"
owner:
  username: "bella-orr"
  id: 143103302
  accepted_at: "2026-08-27T20:43:47Z"
source:
  owner: "IT4063C-Fall2026"
  owner_id: 320344006
  repo: "hello-github"
  branch: "main"
